### python libraries

## numpy


### create one dimensional array

In [3]:
import numpy as np
x=np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [2]:
type(x)

numpy.ndarray

## 2-dimensional array

In [4]:
import numpy as np
y=np.array([[1,2,3],[4,5,6]])
print(y)

[[1 2 3]
 [4 5 6]]


## 3-dimensional array

In [5]:
import numpy as np
z=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(z)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [6]:
a=[[1,2,3],[4,5,6],[7,8,9]]
z=np.array(a)
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
z[0]

array([1, 2, 3])

In [9]:
z[1]

array([4, 5, 6])

In [8]:
z[0][1]

2

In [12]:
z[2][2]

9

In [13]:
y.ndim

2

In [14]:
z.shape

(3, 3)

In [15]:
z.size

9

In [18]:
s=np.array([1,2,3,4,5,6],ndmin=2)
print(s)

[[1 2 3 4 5 6]]


In [20]:
s=np.array([3,4,1,5,2],dtype=complex)
print(s)

[3.+0.j 4.+0.j 1.+0.j 5.+0.j 2.+0.j]


## array sciling

In [22]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
x[:6]

array([0, 1, 2, 3, 4, 5])

In [24]:
x[1::2]

array([1, 3, 5, 7, 9])

In [25]:
x[0:8:2]

array([0, 2, 4, 6])

In [26]:
n=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,6,8]]])
print(n)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 6 8]]]


## reshaping of array

In [34]:
s=np.arange(1,10).reshape((3,3))
print(s)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## concatination of arrays

In [38]:
x=np.array([1,2,3])
y=np.array([4,5,6])
z=np.concatenate([x,y])
print(z)

[1 2 3 4 5 6]


In [39]:
z[2]+z[5]

9

## splitting of arrays

In [40]:
x=[1,2,3,9,9,3,2,1]
x1,x2,x3=np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [9 9] [3 2 1]


In [41]:
a1=np.arange(10000)
a1

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [42]:
a2=np.arange(10000).reshape(100,100)
print(a2)

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [43]:
a3=np.arange(100).reshape(10,10)
print(a3)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [44]:
a4=np.arange(12).reshape(2,6)
print(a4)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [46]:
s1=np.ones((3,3))
print(s1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [49]:
s2=s1+2
print(s2)

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [50]:
s3=s2+2
s3

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [51]:
s4=s3*7
s4

array([[35., 35., 35.],
       [35., 35., 35.],
       [35., 35., 35.]])

In [52]:
a=[1,2,3]
a1=np.array(a)
print(a1)

[1 2 3]


In [58]:
print(np.sqrt(a1))

[1.         1.41421356 1.73205081]


In [54]:
print(np.sin(a1))

[0.84147098 0.90929743 0.14112001]


In [56]:
print(np.tan(a1))

[ 1.55740772 -2.18503986 -0.14254654]


In [57]:
print(np.log(a1))

[0.         0.69314718 1.09861229]


In [59]:
x=np.random.rand(2,5)
print(x)

[[0.6010921  0.21930736 0.60358294 0.50641312 0.23490391]
 [0.23992835 0.56672238 0.7448607  0.46187748 0.08526452]]


In [60]:
x1=np.random.randint(3,size=10)
print(x1)

[2 2 0 1 1 1 1 2 1 2]


In [61]:
x2=np.random.ranf(3)
print(x2)

[0.51088106 0.04569105 0.36405124]


In [62]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [63]:
print(len(dir(np)))

620


In [64]:
np.__version__

'1.19.2'

## filtering arrays

In [66]:
import numpy as np
ary = np.array([11,12,13,14])
print(ary)
'''x=[true,flase,true,flase]
nary=ary[x]
print(nary)'''

[11 12 13 14]


'x=[true,flase,true,flase]\nnary=ary[x]\nprint(nary)'

In [70]:
import numpy as np
ary = np.array([11,12,13,14])
#print(ary)
x = [True,False,True,False]
nary=ary[x]
print(nary)

[11 13]


## create filter array for even elements

In [71]:
ar=np.array([1,2,3,4,5,6,7])
filter_ar=ar%2==0
new_ar=ar[filter_ar]
print(filter_ar)
print(new_ar)

[False  True False  True False  True False]
[2 4 6]


## statistical array

In [3]:
import numpy as np
np.sum(np.array([3,7,5,8]))

23

In [4]:
from numpy import sum,array

In [6]:
sum(array([1,2,3,4,5]))

15

## agenda

In [ ]:
 -pandas
     -series
     -dataframes   

In [7]:
import pandas as pd

In [8]:
pd.__version__

'1.1.3'

In [9]:
print(dir(pd))

['BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_hashtable', '_is_numpy_dev', '_lib', '_libs', '_np_version_under1p16', '_np_version_under1p17', '_np_version_under1p18', '_testing', '_tslib', '_typing', '_version', 'api', 'array', 'arrays', 'bdate_range', 'comp

In [10]:
print(len(dir(pd)))

140


## pandas series

In [32]:
import pandas as pd
import numpy as np

In [33]:
r=pd.Series(np.array([1,2,3,4,5,6]),index=['a','b','c','d','e','f'])

In [34]:
r

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int32

In [35]:
r=pd.Series(np.array([1,2,3,4,5,6]),index=['a','b','c','d','e','f'],name='roll no')

In [36]:
r

a    1
b    2
c    3
d    4
e    5
f    6
Name: roll no, dtype: int32

In [37]:
r=pd.Series(np.array([1,2,3,4,5,6]),index=['a','b','c','d','e','f'],name='roll no',dtype='float')

In [38]:
r

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
f    6.0
Name: roll no, dtype: float64

In [41]:
d = {'a1':99,'a2':32,'a3':67,'a4':95,'a5':78}
d.keys()

dict_keys(['a1', 'a2', 'a3', 'a4', 'a5'])

In [42]:
d = {'a1':99,'a2':32,'a3':67,'a4':95,'a5':78}
d.values()

dict_values([99, 32, 67, 95, 78])

In [43]:
d = {'a1':99,'a2':32,'a3':67,'a4':95,'a5':78}
d.items()

dict_items([('a1', 99), ('a2', 32), ('a3', 67), ('a4', 95), ('a5', 78)])

In [45]:
marks = pd.Series(d,name='S Marks',dtype='str')
print(marks)

a1    99
a2    32
a3    67
a4    95
a5    78
Name: S Marks, dtype: object


In [46]:
marks['a1']

'99'

In [47]:
marks[['a1','a2']]

a1    99
a2    32
Name: S Marks, dtype: object

In [48]:
marks['a1':'a4']

a1    99
a2    32
a3    67
a4    95
Name: S Marks, dtype: object

In [49]:
# iloc - it defines index values
# loc - it defines index positions
marks.iloc[0]

'99'

In [50]:
marks.loc['a1']

'99'

In [51]:
marks.iloc[0:4]

a1    99
a2    32
a3    67
a4    95
Name: S Marks, dtype: object

In [54]:
import random

In [55]:
random.randint(1,10)

10

In [59]:
b = pd.Series(np.array([9,7,6,5,4,3,8]),index=list('ABCDEFG'),name='grades')
b

A    9
B    7
C    6
D    5
E    4
F    3
G    8
Name: grades, dtype: int32

In [60]:
b > 6

A     True
B     True
C    False
D    False
E    False
F    False
G     True
Name: grades, dtype: bool

In [61]:
b[b > 6]

A    9
B    7
G    8
Name: grades, dtype: int32

In [62]:
b*10

A    90
B    70
C    60
D    50
E    40
F    30
G    80
Name: grades, dtype: int32

# statistical operations

In [64]:
b.mean()

6.0

In [68]:
b['A':'D'].mean()

6.75

In [69]:
(9+7+6)/3

7.333333333333333

In [71]:
b['b']=23
b

A     9
B     7
C     6
D     5
E     4
F     3
G     8
b    23
Name: grades, dtype: int64

# probably the important data stuctures of pandas is the dataframes.its a tabular structure tightly interacted with series

In [141]:
ms_marks={'sub1':[98,67,89,57,86,83,62,33,98,95],
         'sub2':[76,84,92,23,54,90,80,70,60,100],
         'sub3':[89,75,54,78,57,47,67,86,65,78],
         'sub4':[98,56,66,98,78,56,67,67,98,89]}

In [142]:
marks = pd.DataFrame(ms_marks,index=['poojitha','vidya','hansika','usha','bhavitha','priya','seema','reema','divya','jyothi'])
marks

sub1  sub2  sub3  sub4
poojitha    98    76    89    98
vidya       67    84    75    56
hansika     89    92    54    66
usha        57    23    78    98
bhavitha    86    54    57    78
priya       83    90    47    56
seema       62    80    67    67
reema       33    70    86    67
divya       98    60    65    98
jyothi      95   100    78    89

In [143]:
marks.loc['poojitha'].sum()

361

In [144]:
marks.loc[['poojitha','usha']].sum()

sub1    155
sub2     99
sub3    167
sub4    196
dtype: int64

In [145]:
marks.columns

Index(['sub1', 'sub2', 'sub3', 'sub4'], dtype='object')

In [146]:
marks.info

<bound method DataFrame.info of           sub1  sub2  sub3  sub4
poojitha    98    76    89    98
vidya       67    84    75    56
hansika     89    92    54    66
usha        57    23    78    98
bhavitha    86    54    57    78
priya       83    90    47    56
seema       62    80    67    67
reema       33    70    86    67
divya       98    60    65    98
jyothi      95   100    78    89>

In [147]:
marks.size

40

In [148]:
marks.shape

(10, 4)

In [149]:
marks.describe()

sub1        sub2       sub3       sub4
count  10.000000   10.000000  10.000000  10.000000
mean   76.800000   72.900000  69.600000  77.300000
std    21.415467   22.600147  13.969809  17.224337
min    33.000000   23.000000  47.000000  56.000000
25%    63.250000   62.500000  59.000000  66.250000
50%    84.500000   78.000000  71.000000  72.500000
75%    93.500000   88.500000  78.000000  95.750000
max    98.000000  100.000000  89.000000  98.000000

In [150]:
marks['sub1']

poojitha    98
vidya       67
hansika     89
usha        57
bhavitha    86
priya       83
seema       62
reema       33
divya       98
jyothi      95
Name: sub1, dtype: int64

In [151]:
marks[['sub1','sub4']]

sub1  sub4
poojitha    98    98
vidya       67    56
hansika     89    66
usha        57    98
bhavitha    86    78
priya       83    56
seema       62    67
reema       33    67
divya       98    98
jyothi      95    89

In [152]:
marks[marks>70]

sub1   sub2  sub3  sub4
poojitha  98.0   76.0  89.0  98.0
vidya      NaN   84.0  75.0   NaN
hansika   89.0   92.0   NaN   NaN
usha       NaN    NaN  78.0  98.0
bhavitha  86.0    NaN   NaN  78.0
priya     83.0   90.0   NaN   NaN
seema      NaN   80.0   NaN   NaN
reema      NaN    NaN  86.0   NaN
divya     98.0    NaN   NaN  98.0
jyothi    95.0  100.0  78.0  89.0

In [153]:
marks.sub1['usha']

57

In [154]:
marks.iloc[0][0:3]

sub1    98
sub2    76
sub3    89
Name: poojitha, dtype: int64

In [155]:
marks.iloc[0][0:3]
marks

sub1  sub2  sub3  sub4
poojitha    98    76    89    98
vidya       67    84    75    56
hansika     89    92    54    66
usha        57    23    78    98
bhavitha    86    54    57    78
priya       83    90    47    56
seema       62    80    67    67
reema       33    70    86    67
divya       98    60    65    98
jyothi      95   100    78    89

In [156]:
marks.iloc[1][2]

75

In [158]:
marks['sub5']=[20,12,34,56,67,87,90,89,45,76]
marks

sub1  sub2  sub3  sub4  sub5
poojitha    98    76    89    98    20
vidya       67    84    75    56    12
hansika     89    92    54    66    34
usha        57    23    78    98    56
bhavitha    86    54    57    78    67
priya       83    90    47    56    87
seema       62    80    67    67    90
reema       33    70    86    67    89
divya       98    60    65    98    45
jyothi      95   100    78    89    76

# how to drop columns

In [159]:
marks.drop(columns='sub5')

sub1  sub2  sub3  sub4
poojitha    98    76    89    98
vidya       67    84    75    56
hansika     89    92    54    66
usha        57    23    78    98
bhavitha    86    54    57    78
priya       83    90    47    56
seema       62    80    67    67
reema       33    70    86    67
divya       98    60    65    98
jyothi      95   100    78    89

In [160]:
marks.drop(columns=['sub5','sub4'])

sub1  sub2  sub3
poojitha    98    76    89
vidya       67    84    75
hansika     89    92    54
usha        57    23    78
bhavitha    86    54    57
priya       83    90    47
seema       62    80    67
reema       33    70    86
divya       98    60    65
jyothi      95   100    78

In [161]:
marks

sub1  sub2  sub3  sub4  sub5
poojitha    98    76    89    98    20
vidya       67    84    75    56    12
hansika     89    92    54    66    34
usha        57    23    78    98    56
bhavitha    86    54    57    78    67
priya       83    90    47    56    87
seema       62    80    67    67    90
reema       33    70    86    67    89
divya       98    60    65    98    45
jyothi      95   100    78    89    76

In [162]:
marks.drop(columns='sub5',axis=1,inplace=True)

In [163]:
marks

sub1  sub2  sub3  sub4
poojitha    98    76    89    98
vidya       67    84    75    56
hansika     89    92    54    66
usha        57    23    78    98
bhavitha    86    54    57    78
priya       83    90    47    56
seema       62    80    67    67
reema       33    70    86    67
divya       98    60    65    98
jyothi      95   100    78    89

In [164]:
marks.sub3[0:10]=100

In [165]:
marks

sub1  sub2  sub3  sub4
poojitha    98    76   100    98
vidya       67    84   100    56
hansika     89    92   100    66
usha        57    23   100    98
bhavitha    86    54   100    78
priya       83    90   100    56
seema       62    80   100    67
reema       33    70   100    67
divya       98    60   100    98
jyothi      95   100   100    89

In [ ]:
marks.iloc[:][:]=100

In [167]:
marks

sub1  sub2  sub3  sub4
poojitha    98    76   100    98
vidya       67    84   100    56
hansika     89    92   100    66
usha        57    23   100    98
bhavitha    86    54   100    78
priya       83    90   100    56
seema       62    80   100    67
reema       33    70   100    67
divya       98    60   100    98
jyothi      95   100   100    89

In [ ]:
import pandas as pd

In [169]:
pop_data = pd.read_csv('marks.csv')

In [170]:
pop_data

2001   2002  2003  2004  2005  2006  2007  2008   2009   2010
0    91   91.5    90    95    92    97    98    99   91.5   99.6
1   120  121.9   125   130   131   129   676   123  658.7  345.0
2    91   91.5    90    95    92    97    98    99   91.5   99.6
3   120  121.9   125   130   131   129   676   123  658.7  345.0
4    91   91.5    90    95    92    97    98    99   91.5   99.6
5   120  121.9   125   130   131   129   676   123  658.7  345.0
6    91   91.5    90    95    92    97    98    99   91.5   99.6
7   120  121.9   125   130   131   129   676   123  658.7  345.0
8    91   91.5    90    95    92    97    98    99   91.5   99.6
9   120  121.9   125   130   131   129   676   123  658.7  345.0

In [171]:
pop_data.index

RangeIndex(start=0, stop=10, step=1)

In [172]:
pop_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   2001    10 non-null     int64  
 1   2002    10 non-null     float64
 2   2003    10 non-null     int64  
 3   2004    10 non-null     int64  
 4   2005    10 non-null     int64  
 5   2006    10 non-null     int64  
 6   2007    10 non-null     int64  
 7   2008    10 non-null     int64  
 8   2009    10 non-null     float64
 9   2010    10 non-null     float64
dtypes: float64(3), int64(7)
memory usage: 928.0 bytes


In [175]:
pop_data.index=['india','china','englang','south korea','north korea','america','maldives','paksitan','nepal','africa']

In [176]:
pop_data

2001   2002  2003  2004  2005  2006  2007  2008   2009   2010
india          91   91.5    90    95    92    97    98    99   91.5   99.6
china         120  121.9   125   130   131   129   676   123  658.7  345.0
englang        91   91.5    90    95    92    97    98    99   91.5   99.6
south korea   120  121.9   125   130   131   129   676   123  658.7  345.0
north korea    91   91.5    90    95    92    97    98    99   91.5   99.6
america       120  121.9   125   130   131   129   676   123  658.7  345.0
maldives       91   91.5    90    95    92    97    98    99   91.5   99.6
paksitan      120  121.9   125   130   131   129   676   123  658.7  345.0
nepal          91   91.5    90    95    92    97    98    99   91.5   99.6
africa        120  121.9   125   130   131   129   676   123  658.7  345.0

In [184]:
book2=pd.read_excel('book2.xlsx')


In [185]:
book2

Unnamed: 0  sub1  sub2  sub3
0   poojitha    34    56    67
1       usha    22    43    65
2   bhavitha    55    66    78
3    hansika    44    46    78
4      vidya    76    76    76
5      seema    32    42    43
6      reema    55    43    45
7      divya    66    89     9
8     jyothi    44    65    89

In [13]:
mydata=np.arange(30,100)
print(mydata)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77
 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [14]:
mydata=np.arange(30,100,10)
print(mydata)

[30 40 50 60 70 80 90]


In [16]:
mypop_data=pd.Series(mydata)
print(mypop_data)

0    30
1    40
2    50
3    60
4    70
5    80
6    90
dtype: int32


In [17]:
mypop_data.name="population"

In [19]:
mypop_data.dtype

dtype('int32')

In [20]:
mypop_data[0]

30

In [21]:
mypop_data[1:4]

1    40
2    50
3    60
Name: population, dtype: int32

In [18]:
mypop_data.name

'population'

In [26]:
g7_pop = pd.Series([54.567,45.3447,54.567,123.45,89.766])

In [27]:
g7_pop.index

RangeIndex(start=0, stop=5, step=1)

In [29]:
mypop_data.index

RangeIndex(start=0, stop=7, step=1)

In [30]:
mypop_data.index=['a','b','c','d','e','f','g']